In [43]:
#3 diffetent iterative method to solve Ax=b
#(a)Jacobi's Method
#(b)Gauss-Seidel Method
#(c)Successive Over-Relaxation(SOR) Method (find optimal omega)
#(d)comparison

#usage = for biweekly quiz 6 for class PMS.CM Chang @ NCTU AM 11
#Biweekly quiz 5 iterative technique in matrix algebra 20191115 ch7
#Pactice of Mathematics Software

#author = maxwill lin =  yt lin
#school number = 0712238@NCTU

#created 2019.11.15
#modified 2019.11.29
#exp on 1e-5 for update : Jacobi : 26 / Gauss-Seidel : 15 / SOR(w = 1.0862172434486896) : 12

#show ans by printing out

In [2]:
import numpy as np

In [3]:
A = np.eye(12)*4
for i in range(0,3):
    A[i][i+1] = A[i+1][i] = -1
for i in range(0,3):
    A[11-i][10-i] = A[10-i][11-i] = -1
for i in range(0,4):
    A[5+i][3+i] = A[3+i][5+i] = -1 
A[4][0] = A[0][4] = -1
A[7][11] = A[11][7] = -1
print(A)
b = np.asarray([220, 110, 110, 220, 110, 110, 110, 110, 220, 110, 110, 220]).T

eps = 1e-5
x0 = np.zeros(A.shape[0])

[[ 4. -1.  0.  0. -1.  0.  0.  0.  0.  0.  0.  0.]
 [-1.  4. -1.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
 [ 0. -1.  4. -1.  0.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0. -1.  4.  0. -1.  0.  0.  0.  0.  0.  0.]
 [-1.  0.  0.  0.  4.  0. -1.  0.  0.  0.  0.  0.]
 [ 0.  0.  0. -1.  0.  4.  0. -1.  0.  0.  0.  0.]
 [ 0.  0.  0.  0. -1.  0.  4.  0. -1.  0.  0.  0.]
 [ 0.  0.  0.  0.  0. -1.  0.  4.  0.  0.  0. -1.]
 [ 0.  0.  0.  0.  0.  0. -1.  0.  4. -1.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0. -1.  4. -1.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.  0. -1.  4. -1.]
 [ 0.  0.  0.  0.  0.  0.  0. -1.  0.  0. -1.  4.]]


In [4]:
Ainv = np.linalg.inv(A)
print("direct solution:")
print(np.dot(Ainv, b))


direct solution:
[88. 66. 66. 88. 66. 66. 66. 66. 88. 66. 66. 88.]


In [5]:
def Jacobi(A, b, x0=x0, eps=eps, N=30):
    print("Solving Ax = b with Jacobi method...")                                                                                                                                                      
    if x0 is None:
        x0 = np.zeros(A.shape[0])
                                                                                                                                                                
    M = np.diagflat(np.diag(A))
    AM = A - M                                                                                                                                                              
    for i in range(N):
        if(np.linalg.norm((np.dot(A,x0)-b)) < eps):
            print("norm Ax-b < eps @ iteration {}".format(i))
            return x0
        print("interation {}:\n".format(i), x0)
        x1 = np.dot(np.linalg.inv(M), b - np.dot(AM, x0)) #in here
        x0 = x1
    return x0

In [6]:
Jacobi(A,b)

Solving Ax = b with Jacobi method...
interation 0:
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
interation 1:
 [55.  27.5 27.5 55.  27.5 27.5 27.5 27.5 55.  27.5 27.5 55. ]
interation 2:
 [68.75  48.125 48.125 68.75  48.125 48.125 48.125 48.125 68.75  48.125
 48.125 68.75 ]
interation 3:
 [79.0625  56.71875 56.71875 79.0625  56.71875 56.71875 56.71875 56.71875
 79.0625  56.71875 56.71875 79.0625 ]
interation 4:
 [83.359375  61.4453125 61.4453125 83.359375  61.4453125 61.4453125
 61.4453125 61.4453125 83.359375  61.4453125 61.4453125 83.359375 ]
interation 5:
 [85.72265625 63.70117188 63.70117188 85.72265625 63.70117188 63.70117188
 63.70117188 63.70117188 85.72265625 63.70117188 63.70117188 85.72265625]
interation 6:
 [86.85058594 64.85595703 64.85595703 86.85058594 64.85595703 64.85595703
 64.85595703 64.85595703 86.85058594 64.85595703 64.85595703 86.85058594]
interation 7:
 [87.42797852 65.42663574 65.42663574 87.42797852 65.42663574 65.42663574
 65.42663574 65.42663574 87.42797852 65.426

array([87.99999891, 65.99999891, 65.99999891, 87.99999891, 65.99999891,
       65.99999891, 65.99999891, 65.99999891, 87.99999891, 65.99999891,
       65.99999891, 87.99999891])

In [7]:
def Gauss_Seidel(A, b, x0=x0, eps=eps, N=30):
    print("Solving Ax = b with Gauss Seidel method...")                                                                                                                                                      
    if x0 is None:
        x0 = np.zeros(A.shape[0])

    M = np.tril(A)
    AM = A - M
    for i in range(N):
        if(np.linalg.norm((np.dot(A,x0)-b)) < eps):
            print("norm Ax-b < eps @ iteration {}".format(i))
            return x0
        print("interation {}:\n".format(i), x0)
        x1 = np.dot(np.linalg.inv(M), b - np.dot(AM, x0))
        x0 = x1
    return x0

In [9]:
Gauss_Seidel(A,b)

Solving Ax = b with Gauss Seidel method...
interation 0:
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
interation 1:
 [55.         41.25       37.8125     64.453125   41.25       43.61328125
 37.8125     38.40332031 64.453125   43.61328125 38.40332031 74.20166016]
interation 2:
 [75.625      55.859375   57.578125   80.29785156 55.859375   57.17529297
 57.578125   60.34423828 80.29785156 57.17529297 60.34423828 85.17211914]
interation 3:
 [82.9296875  62.62695312 63.23120117 85.10162354 62.62695312 63.86146545
 63.23120117 64.75839615 85.10162354 63.86146545 64.75839615 87.37919807]
interation 4:
 [86.31347656 64.88616943 64.99694824 87.21460342 64.88616943 65.49324989
 64.99694824 65.71811199 87.21460342 65.49324989 65.71811199 87.859056  ]
interation 5:
 [87.44308472 65.61000824 65.70615292 87.7998507  65.61000824 65.87949067
 65.70615292 65.93463667 87.7998507  65.87949067 65.93463667 87.96731833]
interation 6:
 [87.80500412 65.87778926 65.91940999 87.94972517 65.87778926 65.97109046
 65.91

array([87.99999852, 65.99999925, 65.99999962, 87.99999981, 65.99999925,
       65.9999999 , 65.99999962, 65.99999995, 87.99999981, 65.9999999 ,
       65.99999995, 87.99999998])

In [35]:
def SOR(A, b, w, x0=x0, eps=eps, N=30, show=True):
    if show:
        print("Solving Ax = b with SOR method, w = {}...".format(w))                                                                                                                                                      
    if x0 is None:
        x0 = np.zeros(A.shape[0])

    D = np.diagflat(np.diag(A))
    L = np.tril(A)-D
    M = D+w*L
    AM = A - M                   
    for i in range(N):
        if(np.linalg.norm((np.dot(A,x0)-b)) < eps):
            if show:
                print("norm Ax-b < eps @ iteration {}".format(i))
            return x0, i
        if show:
            print("interation {}:\n".format(i), x0)
        x1 = np.dot(np.linalg.inv(M), b - np.dot(AM, x0))
        x0 = x1
    return x0, N

In [48]:
SOR(A, b, 1.0862172434486896) #1.1-1.3, 9it, 1.1 13 1e-5

Solving Ax = b with SOR method, w = 1.0862172434486896...
interation 0:
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
interation 1:
 [55.         42.4354871  39.02353945 65.59701036 42.4354871  45.31315094
 39.02353945 39.80498148 65.59701036 45.31315094 39.80498148 76.61842863]
interation 2:
 [76.21774355 56.76765459 58.40008623 81.34595741 56.76765459 58.12719242
 58.40008623 61.4626031  81.34595741 58.12719242 61.4626031  86.66493177]
interation 3:
 [83.3838273  63.10043838 63.74809774 85.58409524 63.10043838 64.35302472
 63.74809774 65.38868265 85.58409524 64.35302472 65.38868265 87.8635892 ]
interation 4:
 [86.55021919 65.14282863 65.22575328 87.42654435 65.14282863 65.74351947
 65.22575328 65.93174832 87.42654435 65.74351947 65.93174832 87.98928497]
interation 5:
 [87.57141431 65.72130306 65.79943047 87.8981027  65.72130306 65.96762687
 65.79943047 65.99405844 87.8981027  65.96762687 65.99405844 87.99971532]
interation 6:
 [87.86065153 65.92125481 65.9591492  87.98513664 65.92125481 65.

(array([87.99999777, 66.00000014, 66.00000028, 88.00000013, 66.00000014,
        66.00000004, 66.00000028, 66.00000001, 88.00000013, 66.00000004,
        66.00000001, 88.        ]), 12)

In [46]:
#run to find minw for SOR
ws = np.linspace(0.0, 2.0, 5000)
minit = 30;
minw = 0.0;
for wi in ws:
    xi, ri = SOR(A, b, wi, show=False)
    if(ri < minit):
        minw = wi
        minit = ri
    

In [47]:
minw, minit

(1.0862172434486896, 12)