In [97]:
#use different method to find a certain eigenvalue and eigenvector pair
#(a)Power Method (max eigenvalue)
#(b)Symmetric Power Method (max eigenvalue)
#(c)Inverse Power Method (min eigenvalue)
#(d)Inverse Power Method closest to 2.5
#(e)Varaiant Inverse Power Method closest to 2.5

#usage = for biweekly quiz 5 for class PMS.CM Chang @ NCTU AM 11
#Biweekly quiz 7 power method and its variants
#Pactice of Mathematics Software

#author = maxwill lin =  yt lin
#school number = 0712238@NCTU

#created 2019.12.24
#modified 

#show ans by printing out

In [104]:
import numpy as np
import scipy
import scipy.linalg

In [99]:
A = np.eye(12)*4
for i in range(0,3):
    A[i][i+1] = A[i+1][i] = -1
for i in range(0,3):
    A[11-i][10-i] = A[10-i][11-i] = -1
for i in range(0,4):
    A[5+i][3+i] = A[3+i][5+i] = -1 
A[4][0] = A[0][4] = -1
A[7][11] = A[11][7] = -1
print(A)
b = np.asarray([220, 110, 110, 220, 110, 110, 110, 110, 220, 110, 110, 220]).T

eps = 1e-5
x0 = np.zeros(A.shape[0])

[[ 4. -1.  0.  0. -1.  0.  0.  0.  0.  0.  0.  0.]
 [-1.  4. -1.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
 [ 0. -1.  4. -1.  0.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0. -1.  4.  0. -1.  0.  0.  0.  0.  0.  0.]
 [-1.  0.  0.  0.  4.  0. -1.  0.  0.  0.  0.  0.]
 [ 0.  0.  0. -1.  0.  4.  0. -1.  0.  0.  0.  0.]
 [ 0.  0.  0.  0. -1.  0.  4.  0. -1.  0.  0.  0.]
 [ 0.  0.  0.  0.  0. -1.  0.  4.  0.  0.  0. -1.]
 [ 0.  0.  0.  0.  0.  0. -1.  0.  4. -1.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0. -1.  4. -1.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.  0. -1.  4. -1.]
 [ 0.  0.  0.  0.  0.  0.  0. -1.  0.  0. -1.  4.]]


In [175]:
def PowerIteration(A, v=None, eps=10e-10, max_iter=1500):
    if v == None:
        v = np.random.randn(A.shape[0])
        v /= np.linalg.norm(v)
    for t in range(max_iter):
        y = np.dot(A, v)
        if(np.linalg.norm(y) < eps):
            print("A has eigencalue 0, try anothor x0")
            return 0, y
        #Rayleigh quotient
        lamb = v.dot(np.dot(A,v))/v.dot(v)
        err = np.linalg.norm(v-y/np.linalg.norm(y))
        if err < eps:
            print("Converge at {} iteration(with diff), v = ".format(t), '\n',v)
            return lamb, v
        v = y/np.linalg.norm(y)
    print("Use Max iteration {} still dont converge, v = ".format(max_iter), '\n',v)
    return lamb, v

In [176]:
PowerIteration(A, v=None, eps=1e-10, max_iter=1500)

Converge at 484 iteration(with diff), v =  
 [ 0.28867513 -0.28867513  0.28867514 -0.28867514 -0.28867513  0.28867514
  0.28867513 -0.28867514 -0.28867513  0.28867513 -0.28867513  0.28867513]


(6.000000000000001,
 array([ 0.28867513, -0.28867513,  0.28867514, -0.28867514, -0.28867513,
         0.28867514,  0.28867513, -0.28867514, -0.28867513,  0.28867513,
        -0.28867513,  0.28867513]))

In [190]:
#A should be symmetric
def SymmetricPowerIteration(A, v=None, eps=10e-10, max_iter=500):
    assert(A.T.all() == A.all())
    if v == None:
        v = np.random.randn(A.shape[0])
        v /= np.linalg.norm(v)
        print("x0 = \n", v)
    for t in range(max_iter):
        y = np.dot(A, v)
        #use this mu, no Rayleigh quotient
        mu = np.dot(v.T, y)
        if(np.linalg.norm(y) < eps):
            print("A has eigencalue 0, try anothor x0")
            return 0, y
        err = np.linalg.norm(v-y/np.linalg.norm(y))
        if err < eps:
            print("Converge at {} iteration(with diff), v = ".format(t), '\n',v)
            return mu, v
        v = y/np.linalg.norm(y)
        print("{}\n".format(mu), y)
    print("Use Max iteration {} still dont converge, v = ".format(max_iter), '\n',v)
    return mu, v

In [191]:
SymmetricPowerIteration(A, v=None, eps=10e-10, max_iter=500)

x0 = 
 [ 0.09643874 -0.0792051  -0.11413225  0.11938857 -0.02267533  0.08473452
 -0.04171088  0.13721596 -0.1166856   0.78894063  0.49096819 -0.22757765]
3.6690584976138205
 [ 0.48763539 -0.29912689 -0.49671246  0.50695202 -0.14542916  0.08233356
 -0.02748261  0.69170695 -1.21397213  2.78147993  1.40250977 -1.53849475]
4.387232063414329
 [ 0.62084819 -0.30780127 -0.56889539  0.63305452 -0.27006947 -0.22534309
  0.32388313  1.09466733 -1.97260598  2.83514704  1.13201129 -2.13806627]
4.862516299931029
 [ 0.67755068 -0.28400185 -0.57564382  0.73624597 -0.4481961  -0.58189848
  0.78311299  1.49222698 -2.44558011  2.69606609  0.84790889 -2.38570794]
5.162207930311517
 [ 0.69614035 -0.25033752 -0.55709405  0.8296344  -0.65792936 -0.92135178
  1.21865553  1.80718888 -2.68181012  2.50394007  0.62311211 -2.40303615]
5.356402985748517
 [ 0.70802308 -0.21864731 -0.53831297  0.91972188 -0.87169945 -1.21215629
  1.57493312  2.02334594 -2.77045577  2.31502645  0.45852896 -2.30888867]
5.4819246711732

(6.0, array([ 0.28867514, -0.28867513,  0.28867513, -0.28867513, -0.28867514,
         0.28867513,  0.28867514, -0.28867513, -0.28867514,  0.28867514,
        -0.28867513,  0.28867513]))

In [189]:
def InversePowerIteration(A, v=None, eps=10e-10, max_iter=500):
    if v == None:
        v = np.random.randn(A.shape[0])
        v /= np.linalg.norm(v)
    lu, piv = scipy.linalg.lu_factor(A) # compute LU factorization of A
    for t in range(max_iter):
        y = scipy.linalg.lu_solve((lu, piv), v) #cuse LU fast compute A-1v
        if(np.linalg.norm(y) < eps):
            print("A has eigencalue 0, try anothor x0")
            return 0, v
        lamb = v.dot(np.dot(A,v))/v.dot(v)
        err = np.linalg.norm(v-y/np.linalg.norm(y))
        if err < eps:
            print("Converge at {} iteration(with diff), v = ".format(t), '\n',v)
            return lamb, v
        v = y/np.linalg.norm(y)
    print("Use Max iteration {} still dont converge, v = ".format(max_iter), '\n',v)
    return lamb, v

In [180]:
InversePowerIteration(A, v=None, eps=10e-10, max_iter=500)

Converge at 149 iteration(with diff), v =  
 [0.28867514 0.28867514 0.28867514 0.28867514 0.28867513 0.28867514
 0.28867513 0.28867513 0.28867513 0.28867513 0.28867513 0.28867513]


(2.0000000000000004,
 array([0.28867514, 0.28867514, 0.28867514, 0.28867514, 0.28867513,
        0.28867514, 0.28867513, 0.28867513, 0.28867513, 0.28867513,
        0.28867513, 0.28867513]))

In [181]:
def ShiftedInversePowerIteration(A, mu, eps=10e-10, max_iter=500):
    I = np.identity(A.shape[0])
    v = np.random.randn(A.shape[0])
    v /= np.linalg.norm(v) 
    lu, piv = scipy.linalg.lu_factor(A - mu*I) # compute LU factorization of (A - mu*I)
    for t in range(max_iter):
        y = scipy.linalg.lu_solve((lu, piv), v) #fast compute (A - mu*I)inv*v with LU decomposition
        if(np.linalg.norm(y) < eps):
            print("A has eigencalue 0, try anothor x0")
            return 0, v
        lamb = v.dot(np.dot(A,v))/v.dot(v)
        err = np.linalg.norm(v-y/np.linalg.norm(y))
        if err < eps:
            print("Converge at {} iteration(with diff), v = ".format(t), '\n',v)
            return lamb, v
        v = y/np.linalg.norm(y)
    print("Use Max iteration {} still dont converge, v = ".format(max_iter), '\n',v)
    return v

In [182]:
ShiftedInversePowerIteration(A, mu=2.5)

Use Max iteration 500 still dont converge, v =  
 [ 0.36467715  0.40757648  0.34126602  0.1835136   0.22406288 -0.02341113
  0.02341113 -0.22406288 -0.1835136  -0.34126602 -0.40757648 -0.36467715]


array([ 0.36467715,  0.40757648,  0.34126602,  0.1835136 ,  0.22406288,
       -0.02341113,  0.02341113, -0.22406288, -0.1835136 , -0.34126602,
       -0.40757648, -0.36467715])

In [172]:
#lambda def convergence:
#if(np.linalg.norm(np.dot(A, v)-lamb*v) < eps):
#    print("Converge at {} iteration, v = ".format(t), '\n',v)
#    return lamb, v