In [119]:
#use different method to find a certain eigenvalue and eigenvector pair
#(a)A = LU
#(b)modified LU decomposition and solve Ax=b
#(c)A = LLt, cholesky algorithm
#(d)modidy cholesky algorithm and solve Ax=b

#usage = for biweekly quiz 5 for class PMS.CM Chang @ NCTU AM 11
#Biweekly quiz 5 Matrix Decomposition
#Pactice of Mathematics Software

#author = maxwill lin =  yt lin
#school number = 0712238@NCTU

#created 2019.12.24
#modified 2019.12.27

#show ans by printing out

In [122]:
import numpy as np
import scipy.linalg
np.set_printoptions(suppress=True)

A = np.eye(12)*4
for i in range(0,3):
    A[i][i+1] = A[i+1][i] = -1
for i in range(0,3):
    A[11-i][10-i] = A[10-i][11-i] = -1
for i in range(0,4):
    A[5+i][3+i] = A[3+i][5+i] = -1 
A[4][0] = A[0][4] = -1
A[7][11] = A[11][7] = -1
print(A)
b = np.asarray([220., 110., 110., 220., 110., 110., 110., 110., 220., 110., 110., 220.]).T
print(b)

eps = 1e-5
x0 = np.zeros(A.shape[0])

[[ 4. -1.  0.  0. -1.  0.  0.  0.  0.  0.  0.  0.]
 [-1.  4. -1.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
 [ 0. -1.  4. -1.  0.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0. -1.  4.  0. -1.  0.  0.  0.  0.  0.  0.]
 [-1.  0.  0.  0.  4.  0. -1.  0.  0.  0.  0.  0.]
 [ 0.  0.  0. -1.  0.  4.  0. -1.  0.  0.  0.  0.]
 [ 0.  0.  0.  0. -1.  0.  4.  0. -1.  0.  0.  0.]
 [ 0.  0.  0.  0.  0. -1.  0.  4.  0.  0.  0. -1.]
 [ 0.  0.  0.  0.  0.  0. -1.  0.  4. -1.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0. -1.  4. -1.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.  0. -1.  4. -1.]
 [ 0.  0.  0.  0.  0.  0.  0. -1.  0.  0. -1.  4.]]
[220. 110. 110. 220. 110. 110. 110. 110. 220. 110. 110. 220.]


In [10]:
#direct solve
Ainv = np.linalg.inv(A)
print("direct solution:")
print(np.dot(Ainv, b))

direct solution:
[88. 66. 66. 88. 66. 66. 66. 66. 88. 66. 66. 88.]


In [121]:
print("check for scipy LU library result")
LU0,P0 =  scipy.linalg.lu_factor(A) #store in one matrix
print(LU0) 
#U0 = np.triu(LU0) 
#L0 = np.tril(LU0, -1) 
scipy.linalg.lu_solve((LU0, P0), b)

check for scipy LU library result
[[ 4.         -1.          0.          0.         -1.          0.
   0.          0.          0.          0.          0.          0.        ]
 [-0.25        3.75       -1.          0.         -0.25        0.
   0.          0.          0.          0.          0.          0.        ]
 [ 0.         -0.26666667  3.73333333 -1.         -0.06666667  0.
   0.          0.          0.          0.          0.          0.        ]
 [ 0.          0.         -0.26785714  3.73214286 -0.01785714 -1.
   0.          0.          0.          0.          0.          0.        ]
 [-0.25       -0.06666667 -0.01785714 -0.00478469  3.73205742 -0.00478469
  -1.          0.          0.          0.          0.          0.        ]
 [ 0.          0.          0.         -0.26794258 -0.00128205  3.73205128
  -0.00128205 -1.          0.          0.          0.          0.        ]
 [ 0.          0.          0.          0.         -0.26794872 -0.00034352
   3.73205084 -0.00034352 -1. 

array([88., 66., 66., 88., 66., 66., 66., 66., 88., 66., 66., 88.])

In [117]:
def LU_decomp(A):
    LU = np.copy(A).astype(float)
    n  = len(A)
    for j in range(n-1):
        for i in range(j+1,n):
            LU[i][j] /= LU[j][j]
            for k in range(j+1,n):
                LU[i][k] -= LU[i][j]*LU[j][k]
    return LU

def LU_forwardsub(L,b): 
    n = len(L)
    y = np.copy(b).astype(float)
    for i in range(1,n):
        for j in range(i):
            y[i] -= L[i][j]*y[j]
    return y

def LU_backwardsub(U,y):
    n = len(U)
    x = np.copy(y).astype(float)
    for i in range(n-1,-1,-1):
        for j in range(i+1,n):
            x[i] -= U[i][j]*x[j]
        x[i] /= U[i][i]
    return x

def LU_solve(A,b):
    print("LU decomposition")
    LU = LU_decomp(A) #store in one matrix
    print(LU)
    print("solve for Ly = b")
    y = LU_forwardsub(LU,b)
    print(y)
    print("solve for Uy = x")
    x = LU_backwardsub(LU,y)
    print(x)
    return x

In [118]:
LU_solve(A,b)

LU decomposition
[[ 4.         -1.          0.          0.         -1.          0.
   0.          0.          0.          0.          0.          0.        ]
 [-0.25        3.75       -1.          0.         -0.25        0.
   0.          0.          0.          0.          0.          0.        ]
 [ 0.         -0.26666667  3.73333333 -1.         -0.06666667  0.
   0.          0.          0.          0.          0.          0.        ]
 [ 0.          0.         -0.26785714  3.73214286 -0.01785714 -1.
   0.          0.          0.          0.          0.          0.        ]
 [-0.25       -0.06666667 -0.01785714 -0.00478469  3.73205742 -0.00478469
  -1.          0.          0.          0.          0.          0.        ]
 [ 0.          0.          0.         -0.26794258 -0.00128205  3.73205128
  -0.00128205 -1.          0.          0.          0.          0.        ]
 [ 0.          0.          0.          0.         -0.26794872 -0.00034352
   3.73205084 -0.00034352 -1.          0.      

array([88., 66., 66., 88., 66., 66., 66., 66., 88., 66., 66., 88.])

In [115]:
def Cholesky_decomp(A):
    n = len(A)
    L = np.zeros((n,n)).astype(float)
    for i in range(n):
        for j in range(i+1):
            L[i][j] = A[i][j]
            for k in range(j):
                L[i][j] -= L[i][k]*L[j][k]
            if(i == j):
                L[i][j] = np.sqrt(L[j][j])
            else:
                L[i][j] /= L[j][j]
    return L

def Cholesky_forwardsub(L, b):
    y = b.copy()
    for i in range(len(b)):
        for j in range(i):
            y[i] -= L[i][j]*y[j]
        y[i] /= L[i][i]
    return y
            
def Cholesky_backwardsub(U, y):
    n = len(U)
    x = np.copy(y)
    for i in range(n-1,-1,-1):
        for j in range(i+1,n):
            x[i] -= U[j][i]*x[j]
        x[i] /= U[i][i]
    return x

def Cholesky_solve(A,b):
    L = Cholesky_decomp(A)
    print("Cholesky decomposition\n", L)
    y = Cholesky_forwardsub(L,b)
    print("Solve for Ly = b\n", y)
    x = Cholesky_backwardsub(L,y)
    print("Solve for LTx = y\n", x)
    return x

In [116]:
Cholesky_solve(A,b)

Cholesky decomposition
 [[ 2.          0.          0.          0.          0.          0.
   0.          0.          0.          0.          0.          0.        ]
 [-0.5         1.93649167  0.          0.          0.          0.
   0.          0.          0.          0.          0.          0.        ]
 [ 0.         -0.51639778  1.93218357  0.          0.          0.
   0.          0.          0.          0.          0.          0.        ]
 [ 0.          0.         -0.51754917  1.93187548  0.          0.
   0.          0.          0.          0.          0.          0.        ]
 [-0.5        -0.12909944 -0.03450328 -0.00924342  1.93185336  0.
   0.          0.          0.          0.          0.          0.        ]
 [ 0.          0.          0.         -0.51763171 -0.00247674  1.93185178
   0.          0.          0.          0.          0.          0.        ]
 [ 0.          0.          0.          0.         -0.51763763 -0.00066364
   1.93185166  0.          0.          0.       

array([88., 66., 66., 88., 66., 66., 66., 66., 88., 66., 66., 88.])

In [120]:
print("check for np library result")
Ach = np.linalg.cholesky(A)
print(Ach)
y = np.linalg.solve(Ach, b)
x = np.linalg.solve(Ach.T, y)
print(y, '\n', x)
print("##############################")
print(Cholesky_decomp(A))

check for np library result
[[ 2.          0.          0.          0.          0.          0.
   0.          0.          0.          0.          0.          0.        ]
 [-0.5         1.93649167  0.          0.          0.          0.
   0.          0.          0.          0.          0.          0.        ]
 [ 0.         -0.51639778  1.93218357  0.          0.          0.
   0.          0.          0.          0.          0.          0.        ]
 [ 0.          0.         -0.51754917  1.93187548  0.          0.
   0.          0.          0.          0.          0.          0.        ]
 [-0.5        -0.12909944 -0.03450328 -0.00924342  1.93185336  0.
   0.          0.          0.          0.          0.          0.        ]
 [ 0.          0.          0.         -0.51763171 -0.00247674  1.93185178
   0.          0.          0.          0.          0.          0.        ]
 [ 0.          0.          0.          0.         -0.51763763 -0.00066364
   1.93185166  0.          0.          0.   